purser/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.schemas import get_schema_view
from rest_framework.routers import DefaultRouter
from wallet.urls import router as wallet_router
from accounts.urls import router as accounts_router

main_router = DefaultRouter()

main_router.registry.extend(wallet_router.registry)
main_router.registry.extend(accounts_router.registry)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('wallet.urls')),
    path('accounts/',include('accounts.urls')),
    path('api/',include(main_router.urls)),
    path('openapi/',get_schema_view(
        title="Purser",
        description="eWallet API",
        version="1.0.0"
    ),name="openapi-schema"),
    path('redoc/', TemplateView.as_view(
        template_name='api/redoc.html',
        extra_context={'schema_url':'openapi-schema'}
    ), name='redoc'),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

wallet/urls.py
from rest_framework.routers import DefaultRouter
from .views import (
    WalletViewSet,
    TransactionViewSet,
    SendMoneyViewSet,
    FlutterwaveWebhook
)
from django.urls import path
from .views import (
    WalletList,
    CreateWallet,
    WalletDetail,
    TransactionDetail,
    ApproveTransaction
)
router = DefaultRouter()

router.register(r"wallet",viewset=WalletViewSet)
router.register(r"transaction",viewset=TransactionViewSet)
router.register(r"send-money",viewset=SendMoneyViewSet,basename="send-money")
router.register(r"flutterwave-webhook",viewset=FlutterwaveWebhook,basename="flutterwave")

app_name="wallet"
urlpatterns = [
    path('',WalletList.as_view(), name="list"),
    path('add/',CreateWallet.as_view(),name="create"),
    path('id/<pk>/',WalletDetail.as_view(),name="detail"),
    path('transaction/id/<pk>/',TransactionDetail.as_view(),name="transaction-detail"),
    path('transaction/id/<pk>/approve/',ApproveTransaction.as_view(),name="approve-transaction"),
]

wallet/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

class Wallet(models.Model):
    user=models.ForeignKey(User,related_name="wallets",on_delete=models.CASCADE)
    CURRENCY=(
        ("zmw","ZMW"),
    )
    currency=models.CharField(max_length=200,choices=CURRENCY,default="zmw")
    balance=models.FloatField(default=0.0,editable=False)
    active=models.BooleanField(default=True)
    
    def __str__(self) -> str:
        return str(self.id)

class FlutterwavePayment(models.Model):
    id=models.BigIntegerField(primary_key=True,unique=True)
    tx_ref=models.CharField(max_length=200)
    amount=models.FloatField()
    charged_amount=models.FloatField()
    currency=models.CharField(max_length=200)
    app_fee=models.FloatField()
    merchant_fee=models.FloatField()
    processor_response=models.TextField()
    narration=models.TextField()
    status=models.CharField(max_length=200)
    payment_type=models.CharField(max_length=200)
    created_at=models.DateTimeField()
    
    def __str__(self) -> str:
        return self.tx_ref
    
class FlutterwaveTransfer(models.Model):
    id=models.BigIntegerField(primary_key=True,unique=True)
    account_number=models.CharField(max_length=200)
    bank_name=models.CharField(max_length=200)
    bank_code=models.CharField(max_length=200)
    fullname=models.CharField(max_length=200)
    currency=models.CharField(max_length=200)
    debit_currency=models.CharField(max_length=200)
    amount=models.FloatField()
    fee=models.FloatField()
    status=models.CharField(max_length=200)
    reference=models.CharField(max_length=200)
    narration=models.TextField()
    is_approved=models.BooleanField()
    created_at=models.DateTimeField()
    
    def __str__(self) -> str:
        return self.reference

class Transaction(models.Model):
    antecedent=models.BigIntegerField(null=True)
    tx_ref=models.CharField(max_length=200, unique=True, default=uuid.uuid4())
    wallet=models.ForeignKey(Wallet,related_name="transactions",on_delete=models.CASCADE)
    amount=models.FloatField()
    approved=models.BooleanField(default=False,editable=False)
    
    def __str__(self) -> str:
        return "txn-"+str(self.id)

wallet/forms.py
from django import forms
from .models import (
  Transaction,
  Wallet
)
import uuid

class TransactionForm(forms.Form):
  #antecedent=forms.IntegerField()
  tx_ref=forms.CharField(widget=forms.TextInput(attrs={
    'class':'form-control',
    'placeholder':'Reference'
  }))
  from_wallet=forms.ModelChoiceField(Wallet.objects.all(),required=True,widget=forms.Select(attrs={
    'class':'form-control',
  }))
  amount=forms.FloatField(required=True,widget=forms.NumberInput(attrs={
    'class':'form-control',
    'step':'0.5',
    'placeholder':'Amount'
  }))
  to_wallet=forms.IntegerField(required=True,widget=forms.NumberInput(attrs={
    'class':'form-control',
    'placeholder':'To Wallet ID'
  }))
  
  def __init__(self,*args,**kwargs):
    self.request = kwargs.pop("request")
    super(forms.Form, self).__init__(*args,**kwargs)
    self.fields['from_wallet'].queryset=self.get_queryset()
    self.fields['tx_ref'].initial = uuid.uuid4()
  
  def get_queryset(self):
    return self.request.user.wallets.all()
  
  def save(self):
    #antecendent = Transaction.objects.get(pk=self.cleaned_data["antecedent"])
    from_wallet = self.cleaned_data["from_wallet"]
    to_wallet = Wallet.objects.get(pk=self.cleaned_data["to_wallet"])
    
    antecedent = Transaction.objects.create(
      tx_ref=self.cleaned_data["tx_ref"],
      wallet=from_wallet,
      amount=-1*float(self.cleaned_data["amount"])
    )
    
    transaction = Transaction.objects.create(
      antecedent=antecedent.id,
      wallet=to_wallet,
      amount=float(self.cleaned_data["amount"])
    )
    
    antecedent.antecedent = transaction.id
    antecedent.save()
    
  
  def is_valid(self):
    try:
      to_wallet = Wallet.objects.get(pk=self.data.get("to_wallet"))
    except Wallet.DoesNotExist as e:
      print(e)
      return False
    else:
      return super().is_valid()
  

wallet/views.py
from django.shortcuts import redirect, render
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet, ViewSet
from rest_framework.views import APIView
from rest_framework.decorators import action
from rest_framework.response import Response
from .models import (
    Wallet,
    Transaction
)
from .serializers import (
    WalletSerializer,
    TransactionSerializer,
    SendMoneySerializer,
    FlutterwavePaymentSerializer
)
from rest_framework.permissions import AllowAny
from rest_framework import status
from rest_framework.schemas import ManualSchema
import coreapi
from django.views.generic import (
    ListView,
    DetailView,
    TemplateView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from .forms import TransactionForm

class ApproveTransaction(TemplateView):
    template_name="wallet/approve_transaction.html"
    
    def get(self,request,pk):
        transaction = Transaction.objects.get(pk=pk)
        antecedent = Transaction.objects.get(pk=transaction.antecedent)
        context = {
            "transaction":transaction,
            "antecedent":antecedent
        }
        return render(request, self.template_name, context)

class TransactionDetail(DetailView):
    model=Transaction
    context_object_name="transaction"

class WalletDetail(DetailView):
    model=Wallet
    context_object_name="wallet"
    template_name = "wallet/wallet_detail.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["transfer_form"] = TransactionForm(request=self.request)
        return context
    
    def post(self, request, *args, **kwargs):
        transaction = TransactionForm(request.POST,request=request)
        if transaction.is_valid():
            transaction.save()
            return redirect("wallet:detail",**kwargs)
        else:
            return redirect("wallet:detail",**kwargs)

class CreateWallet(View):
    def get(self,request):
        Wallet.objects.create(user=request.user)
        return redirect("wallet:list")

class WalletList(LoginRequiredMixin,ListView):
    model = Wallet
    context_object_name="wallets"
    def get_queryset(self):
        return self.request.user.wallets.all()

class WalletViewSet(ModelViewSet):
    queryset=Wallet.objects.all()
    serializer_class=WalletSerializer
    permission_classes=[AllowAny]

class TransactionViewSet(ModelViewSet):
    queryset=Transaction.objects.all()
    serializer_class=TransactionSerializer
    permission_classes=[AllowAny]

class SendMoneyViewSet(ViewSet):
    create_schema=ManualSchema(fields=[
        coreapi.Field("from_wallet",True,"form")
    ])
    def create(self,request,schema=create_schema):
        send_money = SendMoneySerializer(data=request.data)
        if send_money.is_valid():
            send_money.save()
            return Response(send_money.data)
        return Response(send_money.errors,status=status.HTTP_400_BAD_REQUEST)

class FlutterwaveWebhook(ViewSet):
    def create(self,request,*args,**kwargs):
        if request.data["event"] == "charge.completed":
            fltxn = FlutterwavePaymentSerializer(data=request.data["data"])
            if fltxn.is_valid():
                fltxn.save()
                txn = Transaction.objects.get(tx_ref=fltxn.data["tx_ref"])
                if fltxn.data["status"] == "successful":
                    txn.approved = True
                    txn.save()
                return Response(TransactionSerializer(txn).data)
            return Response(txn.errors,status=status.HTTP_400_BAD_REQUEST)
        return Response({},status=status.HTTP_400_BAD_REQUEST)

wallet/templates/wallet/approve_transaction.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
  <div class="card text-center mb-3">
    <div class="card-header bg-primary"><h5 class="card-title">Reference: {{transaction.tx_ref}}</h5></div>
    <div class="card-body">
      <h5 class="card-title">{{transaction.wallet.user.username}}:{{transaction.wallet.id}} | {{transaction.amount}} {{transaction.wallet.currency}}</h5>
      {% if transaction.amount < 0 %}
      <hr>
      <p class="card-text">Are you sure you want to approve a transfer of {{antecedent.amount}} {{antecedent.wallet.currency}} to {{antecedent.wallet.user.username}}:{{antecedent.wallet.id}} </p>
      <div class="mb-3">
        {% if not transaction.approved %}
        <div class="mb-3">
          <a href="{% url 'wallet:approve-transaction' pk=transaction.id %}" class="btn btn-success">Approve</a>
        </div>
        <div class="mb-3">
          <button class="btn btn-danger">Decline</button>
        </div>
        {% endif %}
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock main %}

wallet/templates/wallet/transaction_detail.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
  <div class="card text-center mb-3">
    <div class="card-header bg-primary"><h5 class="card-title">Reference: {{transaction.tx_ref}}</h5></div>
    <div class="card-body">
      <h5 class="card-title">{{transaction.wallet.user.username}}:{{transaction.wallet.id}} | {{transaction.amount}} {{transaction.wallet.currency}}</h5>
      {% if transaction.amount < 0 %}
      <hr>
      <div class="mb-3">
        {% if not transaction.approved %}
        <div class="mb-3">
          <a href="{% url 'wallet:approve-transaction' pk=transaction.id %}" class="btn btn-success">Approve</a>
        </div>
        <div class="mb-3">
          <button class="btn btn-danger">Decline</button>
        </div>
        {% endif %}
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock main %}

wallet/templates/wallet/wallet_detail.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
  <div class="card text-center mb-3">
    <div class="card-header bg-primary"><h5 class="card-title">ID:{{wallet.id}}</h5></div>
    <div class="card-body">
      <h5 class="card-title">{{wallet.balance}} {{wallet.currency}}</h5>
      <hr>
      <div class="mb-3">
        <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#transfer-modal">Transfer</button>
        <p class="card-text">{{transfer_form.errors}}</p>
        <div class="modal fade" id="transfer-modal" tabindex="-1" aria-labelledby="transfer-modal-label" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="transfer-modal-label">Transfer</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <form method="post">
                  {% csrf_token %}
                  <div class="form-floating mb-3">
                    {{transfer_form.tx_ref}}
                    <label for="id_tx_ref">Reference</label>
                  </div>
                  <div class="form-floating mb-3">
                    {{transfer_form.from_wallet}}
                    <label for="id_from_wallet">From Wallet ID</label>
                  </div>
                  <div class="form-floating mb-3">
                    {{transfer_form.amount}}
                    <label for="id_amount">Amount</label>
                  </div>
                  <div class="form-floating mb-3">
                    {{transfer_form.to_wallet}}
                    <label for="id_to_wallet">To Wallet ID</label>
                  </div>
                  <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Make Transfer</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Transaction History</h5>
      <div class="list-group">
        {% for transaction in wallet.transactions.all %}
        <a href="{% url 'wallet:transaction-detail' pk=transaction.id %}" class="list-group-item list-group-item-action {% if transaction.approved %}text-success{% else %}text-warning{% endif %}">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{transaction.tx_ref}}</h5>
            <small class="text-muted"></small>
          </div>
          <p class="mb-1">{{transaction.amount}}</p>
        </a>
        {% empty %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          No transactions yet.
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock main %}

wallet/templates/wallet/wallet_list.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
  <div class="row row-cols-1 row-cols-md-2 g-4">
    {% for wallet in wallets %}
    <div class="col">
      <div class="card shadow">
        <div class="card-header"><h5 class="card-title">ID:{{wallet.id}}</h5></div>
        <div class="card-body">
          <h5 class="card-title">{{wallet.balance}} {{wallet.currency}}</h5>
        </div>
        <center><a href="{% url 'wallet:detail' pk=wallet.id %}" class="btn btn-outline-secondary w-100">view</a></center>
      </div>
    </div>
    {% empty %}
    <div class="col">
      <div class="card shadow">
        <div class="card-body">
          <h5 class="card-title">No wallets</h5>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <center class="m-3 p-3 shadow"><a href="{% url 'wallet:create' %}" class="btn btn-outline-primary">Add Wallet</a></center>
</div>
{% endblock main %}