accounts/urls.py
from rest_framework import routers
from django.urls import path
from .views import (
    UserViewSet,
    AccountLogin,
    AccountProfile,
    AccountMain,
    UserRegister
)
from django.contrib.auth.views import logout_then_login

router = routers.DefaultRouter()
router.register(r'user',UserViewSet,basename="user")

app_name="accounts"
urlpatterns = [
    path('login/',AccountLogin.as_view(),name="login"),
    path('logout/',logout_then_login,name="logout"),
    path('id/<pk>/',AccountProfile.as_view(),name="profile"),
    path('',AccountMain.as_view(),name="main"),
    path('profile/',AccountMain.as_view(),name="profile2"),
    path('register/',UserRegister.as_view(),name="register"),
]

purser/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.schemas import get_schema_view
from rest_framework.routers import DefaultRouter
from wallet.urls import router as wallet_router
from accounts.urls import router as accounts_router

main_router = DefaultRouter()

main_router.registry.extend(wallet_router.registry)
main_router.registry.extend(accounts_router.registry)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('wallet.urls')),
    path('accounts/',include('accounts.urls')),
    path('api/',include(main_router.urls)),
    path('openapi/',get_schema_view(
        title="Purser",
        description="eWallet API",
        version="1.0.0"
    ),name="openapi-schema"),
    path('redoc/', TemplateView.as_view(
        template_name='api/redoc.html',
        extra_context={'schema_url':'openapi-schema'}
    ), name='redoc'),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

purser/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Purser</title>
    {% load static %}
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar bg-primary navbar-light shadow mb-3">
      <div class="container">
        <a class="navbar-brand" href="/">Purser</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Wallets</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:main' %}">Account</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    {% block main %}{% endblock main %}
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    {% block jsblock %}{% endblock jsblock %}
  </body>
</html>